import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import NProgressHandler from '@/components/common/nro-progress'
import { ThemeProvider } from '@/components/common/theme-provider'
import AudioPlayer from '@/components/common/AudioPlayer'
import LazyLoading from '@/components/common/lazy-loading'
import AppProvider from '@/components/ui/app-provider'
import { Toaster } from 'sonner'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body className='transition-colors duration-300'>
        <Toaster richColors position='bottom-right' />
        <AppProvider>
          <ThemeProvider attribute='class' defaultTheme='system' enableSystem disableTransitionOnChange>
            {children}
          </ThemeProvider>
        </AppProvider>
        <AudioPlayer />
        <LazyLoading />
        {/* <NProgressHandler /> */}
      </body>
    </html>
  )
}
